### ISSUE TITLE
Missing deliverables to finalise Milestone 2

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#40]
- [ ] transfer could have SignAndSubmit
- [x] review transfer is not working
- [x] tags on create account doesn't work
- [x] filter is broke on accounts

**Comment by vikiival** [comment]
- [x] Submit Preimage
- [x] Hack around data reactivity
- [x] Make sure it's responsive

**Comment by yangwao** [comment]
🎉 we are going for milestone 3
