### ISSUE TITLE
Create meta-tabs router

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/apps#81]
We are using https://buefy.org/documentation/tabs along through explorer, accounts, democracy, toolbox and probably through many others will use this "horizontal routing"

Would be nice to brew very custom reusable component here.

Desired feature sets 
- [ ] entering link like http://localhost:8080/#/explorer/1/0xfb585497ae92327b8e1a79133fd8a8fe867b55fd311f627ca38cd116883c6f4e - will open exact block
- [ ] http://localhost:8080/#/accounts/contacts will open address book
- [ ] when switching tabs, it will update url.
- [ ] http://localhost:8080/#/toolbox/sign/:data - will open dialog to directly sign data - could be once reused in extension later
